blank_issues_enabled: false
contact_links:
  - name: Publication Request Process
    url: https://github.com/elmrec/elm-rec/issues/new/choose
    about: Use the Publication Request issue form for website/Facebook/Instagram requests.
