name: Sync Labels

on:
  workflow_dispatch:
  push:
    paths:
      - .github/labels.yml

permissions:
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync labels from .github/labels.yml
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/labels.yml
          skip-delete: true
